apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onlyoffice.fullname" . }}-local
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  local.json: |
    {
{{- if .Values.settings.maxDocumentSize }}
        "FileConverter": {
            "converter": {
                "maxDownloadBytes": {{ mul .Values.settings.maxDocumentSize 1024 1024 | quote }}
            },
            "inputLimits": [
                {
                    "type": "docx;dotx;docm;dotm",
                    "zip": {
                        "uncompressed": "{{ .Values.settings.maxDocumentSize }}MB",
                        "template": "*.xml"
                    }
                },
                {
                    "type": "xlsx;xltx;xlsm;xltm",
                    "zip": {
                        "uncompressed": "{{ .Values.settings.maxDocumentSize }}MB",
                        "template": "*.xml"
                    }
                },
                {
                    "type": "pptx;ppsx;potx;pptm;ppsm;potm",
                    "zip": {
                        "uncompressed": "{{ .Values.settings.maxDocumentSize }}MB",
                        "template": "*.xml"
                    }
                }
            ]
        }
{{- end }}
    }