{{- if .Values.onlyoffice.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "onlyoffice.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if .Values.onlyoffice.secret.password }}
  onlyoffice-secret: {{ .Values.onlyoffice.secret.password | b64enc | quote }}
{{- else }}
  onlyoffice-secret: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- end }}